version: '3.3'

services:
  heavydb:
    container_name:  {{HEAVYDB_SERVICE_NAME}}
    image: docker-internal.mapd.com/heavyai/heavyai-ee-cuda:8.1.1
    restart: unless-stopped
    ipc: shareable
    volumes:
      - /var/lib/heavyai:/var/lib/heavyai
    networks:
      - heavy-network
    ports:
      - "{{HEAVYDB_PORT}}:{{HEAVYDB_PORT}}"
      - "{{HEAVYDB_BACKEND_PORT}}:{{HEAVYDB_BACKEND_PORT}}"
      - "{{IMMERSE_PORT}}:{{IMMERSE_PORT}}"
      - "{{HEAVYIQ_PORT}}:{{HEAVYIQ_PORT}}"

networks:
  heavy-network:
    driver: bridge
